const fs = require("node:fs");

const createNode = (
  id,
  name,
  category,
  icon,
  brandIcon,
  description,
  inputs,
  credentials,
  outputs,
  setupGuide,
) => ({
  id,
  name,
  category,
  icon,
  brandIcon,
  description,
  inputs,
  credentials: credentials || [],
  outputs,
  setupGuide,
  testAction: `execute${id
    .split("_")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("")}`,
});

const nodes = [
  // ================= START =================
  createNode(
    "manual_trigger",
    "Manual Trigger",
    "trigger",
    "mouse-pointer-click",
    null,
    "Start a workflow manually by clicking a button in the UI.",
    [
      {
        key: "testData",
        label: "Test Data (JSON)",
        type: "json",
        required: false,
        supportsDynamic: false,
        placeholder: '{"test": true}',
      },
    ],
    [],
    [
      {
        key: "triggerTime",
        type: "string",
        description: "ISO timestamp of trigger",
      },
      { key: "data", type: "object", description: "Passed test data" },
    ],
    [
      "Configure optional test JSON payload.",
      "Click 'Test Node' or trigger from canvas.",
    ],
  ),
  createNode(
    "webhook",
    "Webhook Trigger",
    "trigger",
    "webhook",
    null,
    "Trigger your workflow via an external HTTP request.",
    [
      {
        key: "endpoint",
        label: "Webhook URL",
        type: "text",
        required: true,
        supportsDynamic: false,
        placeholder: "Auto-generated upon save",
      },
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: ["POST", "GET", "PUT", "DELETE", "PATCH"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      { key: "body", type: "object", description: "Request body payload" },
      { key: "headers", type: "object", description: "HTTP request headers" },
      { key: "query", type: "object", description: "URL query parameters" },
    ],
    [
      "Copy the auto-generated webhook URL.",
      "Send a test request.",
      "Verify payload in output.",
    ],
  ),
  createNode(
    "google_form",
    "Google Form",
    "trigger",
    "file-text",
    "googleforms",
    "Trigger workflow when a new Google Form response is submitted.",
    [
      {
        key: "formId",
        label: "Form ID",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "googleAuth",
        label: "Google Account",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      { key: "answers", type: "array", description: "Answers submitted" },
      {
        key: "respondentEmail",
        type: "string",
        description: "Email of respondent if collected",
      },
    ],
    [
      "Authenticate Google.",
      "Select your form.",
      "Submit a test response to map fields.",
    ],
  ),
  createNode(
    "stripe_event",
    "Stripe Event",
    "trigger",
    "credit-card",
    "stripe",
    "Trigger on Stripe billing events like payment_intent.succeeded.",
    [
      {
        key: "eventTypes",
        label: "Event Types",
        type: "text",
        required: true,
        supportsDynamic: false,
        placeholder: "invoice.paid, payment_intent.succeeded",
      },
    ],
    [
      {
        key: "stripeKey",
        label: "Stripe API Key",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "event",
        type: "object",
        description: "Stripe event data payload",
      },
    ],
    [
      "Provide Stripe Secret Key.",
      "Select listening events.",
      "Receive test event to set up mapping.",
    ],
  ),
  createNode(
    "schedule",
    "Schedule",
    "trigger",
    "calendar-clock",
    null,
    "Run workflows on a recurring cron schedule.",
    [
      {
        key: "cronExpression",
        label: "CRON Expression",
        type: "text",
        required: true,
        supportsDynamic: false,
        placeholder: "0 0 * * *",
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "select",
        options: ["UTC", "America/New_York", "Europe/London"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "fireTime",
        type: "string",
        description: "Exact time workflow was fired",
      },
    ],
    ["Define your cron schedule.", "Select the appropriate timezone."],
  ),

  // ================= FLOW =================
  createNode(
    "router",
    "Router",
    "flow",
    "git-branch",
    null,
    "Route data to multiple branches simultaneously.",
    [
      {
        key: "branches",
        label: "Number of Branches",
        type: "number",
        required: true,
        supportsDynamic: false,
        placeholder: "2",
      },
    ],
    [],
    [
      { key: "route_1", type: "branch", description: "Path 1" },
      { key: "route_2", type: "branch", description: "Path 2" },
    ],
    [
      "Configure the number of branches.",
      "Connect nodes to each resulting path output.",
    ],
  ),
  createNode(
    "condition",
    "Filter / Condition",
    "flow",
    "split",
    null,
    "Split logic tree based on evaluation conditions.",
    [
      {
        key: "leftValue",
        label: "Compare Target",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "condition",
        label: "Operator",
        type: "select",
        options: ["equals", "contains", "greater than", "less than"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "rightValue",
        label: "Compare Value",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
    ],
    [],
    [
      { key: "result", type: "boolean", description: "Evaluation resolution" },
      { key: "truePath", type: "branch", description: "Path if true" },
      { key: "falsePath", type: "branch", description: "Path if false" },
    ],
    [
      "Select a variable to check.",
      "Define operator requirement.",
      "Map actions to True and False branches.",
    ],
  ),
  createNode(
    "human_approval",
    "Human Approval",
    "flow",
    "user-check",
    null,
    "Pause workflow until a designated user manually approves.",
    [
      {
        key: "approverEmail",
        label: "Approver Email",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "context",
        label: "Context to Review",
        type: "textarea",
        required: false,
        supportsDynamic: true,
      },
    ],
    [],
    [
      { key: "decision", type: "string", description: "approved or rejected" },
      { key: "notes", type: "string", description: "Reviewer comments" },
      { key: "approvedPath", type: "branch", description: "Path if approved" },
      { key: "rejectedPath", type: "branch", description: "Path if rejected" },
    ],
    [
      "Identify the approver.",
      "Provide dynamic context payload.",
      "Workflow halts until button link in email is clicked.",
    ],
  ),
  createNode(
    "delay",
    "Delay",
    "flow",
    "hourglass",
    null,
    "Pause execution logic for a defined duration.",
    [
      {
        key: "duration",
        label: "Delay Value",
        type: "number",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "unit",
        label: "Time Unit",
        type: "select",
        options: ["seconds", "minutes", "hours"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "finishedAt",
        type: "string",
        description: "Resumption timestamp",
      },
    ],
    [
      "Enter duration number.",
      "Select unit of time.",
      "Workflow will transparently pause/re-queue.",
    ],
  ),
  createNode(
    "merge",
    "Merge",
    "flow",
    "git-merge",
    null,
    "Wait for all incoming parent branches to complete before proceeding.",
    [
      {
        key: "waitBehavior",
        label: "Wait For",
        type: "select",
        options: ["all parents", "any parent"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "mergedData",
        type: "object",
        description: "Combined outputs of parents",
      },
    ],
    [
      "Connect multiple nodes into this node.",
      "Select if it should wait for all or any before proceeding.",
    ],
  ),

  // ================= DATA =================
  createNode(
    "http_request",
    "HTTP Request",
    "data",
    "globe",
    null,
    "Call external APIs with custom headers and body.",
    [
      {
        key: "url",
        label: "Request URL",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "method",
        label: "HTTP Method",
        type: "select",
        options: ["GET", "POST", "PUT", "DELETE", "PATCH"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "headers",
        label: "Headers (JSON)",
        type: "json",
        required: false,
        supportsDynamic: true,
      },
      {
        key: "body",
        label: "Request Body",
        type: "textarea",
        required: false,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "apiKey",
        label: "API Key Header (Optional)",
        type: "password",
        required: false,
        supportsDynamic: false,
      },
    ],
    [
      { key: "response.status", type: "number", description: "HTTP Code" },
      { key: "response.body", type: "any", description: "Parsed Body" },
    ],
    [
      "Enter URL.",
      "Select method.",
      "Configure headers.",
      "Test the API configuration.",
    ],
  ),
  createNode(
    "set_variable",
    "Set Variable",
    "data",
    "braces",
    null,
    "Define custom string, number, or object variables for later use.",
    [
      {
        key: "variableName",
        label: "Variable Name",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "variableValue",
        label: "Value",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
    ],
    [],
    [{ key: "value", type: "any", description: "The resolved variable value" }],
    ["Name your variable.", "Set static or dynamic content into it."],
  ),
  createNode(
    "text_template",
    "Text Template",
    "data",
    "file-type-2",
    null,
    "Construct complex strings by combining multiple dynamic variables.",
    [
      {
        key: "template",
        label: "Template Body",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [],
    [
      {
        key: "result",
        type: "string",
        description: "The finalized text output",
      },
    ],
    ["Write base text.", "Inject dynamic node values where needed."],
  ),
  createNode(
    "json_transform",
    "JSON Transform",
    "data",
    "code-xml",
    null,
    "Restructure and extract items from complex JSON objects.",
    [
      {
        key: "sourcePath",
        label: "Source Input",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "extractionKey",
        label: "JMESPath / Key",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "filteredData",
        type: "any",
        description: "Resulting structured JSON",
      },
    ],
    [
      "Select source binding.",
      "Write query or key to extract.",
      "Test extraction.",
    ],
  ),
  createNode(
    "logger",
    "Logger",
    "data",
    "terminal-square",
    null,
    "Output data to the system workflow trace log.",
    [
      {
        key: "logMessage",
        label: "Message / Data",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "level",
        label: "Severity",
        type: "select",
        options: ["info", "warn", "error", "debug"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "logId",
        type: "string",
        description: "Execution log reference trace",
      },
    ],
    [
      "Set log level.",
      "Pass in variables you want to inspect during execution.",
    ],
  ),
  createNode(
    "google_sheets",
    "Google Sheets",
    "data",
    "table",
    "googlesheets",
    "Read, write, or append data directly inside a Google Sheets document.",
    [
      {
        key: "sheetId",
        label: "Spreadsheet ID",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "action",
        label: "Action",
        type: "select",
        options: ["read", "write", "append"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "range",
        label: "Data Range",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "values",
        label: "Values (JSON)",
        type: "json",
        required: false,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "googleAuth",
        label: "Google OAuth Connection",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "rows",
        type: "array",
        description: "Row data from read operation",
      },
      {
        key: "updatedRange",
        type: "string",
        description: "Range that was affected",
      },
    ],
    [
      "Connect Google Auth.",
      "Input Sheet ID.",
      "Select action.",
      "Provide data mapped to columns.",
    ],
  ),
  createNode(
    "email_parser",
    "Email Parser",
    "data",
    "mail-search",
    null,
    "Extract keys and values from raw Email text utilizing RegEx or built-in AI parser.",
    [
      {
        key: "sourceText",
        label: "Raw Email Body",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "parseRules",
        label: "Rules (JSON schema)",
        type: "json",
        required: true,
        supportsDynamic: false,
      },
    ],
    [],
    [
      {
        key: "extractedData",
        type: "object",
        description: "Dictionary of parsed items",
      },
    ],
    [
      "Pass in incoming email body from a webhook/trigger.",
      "Define extraction keys object.",
    ],
  ),
  createNode(
    "database_query",
    "Database Query",
    "data",
    "database",
    null,
    "Run standard SQL commands against Postgres, MySQL, or SQL Server.",
    [
      {
        key: "engine",
        label: "SQL Engine",
        type: "select",
        options: ["postgres", "mysql", "mssql"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "query",
        label: "SQL Query String",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "dbUri",
        label: "Database Connection URI",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "results",
        type: "array",
        description: "Array of returned database records",
      },
    ],
    [
      "Select target engine.",
      "Provide connection securely.",
      "Write SQL query (use bindings for secure parameterized inputs).",
    ],
  ),
  createNode(
    "file_storage",
    "File Storage",
    "data",
    "folder-open",
    null,
    "Interact with remote Blob Storage architectures like S3.",
    [
      {
        key: "action",
        label: "Protocol",
        type: "select",
        options: ["download", "upload", "delete"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "bucket",
        label: "Bucket Name",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "fileId",
        label: "File Key/Path",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "fileData",
        label: "File Buffer",
        type: "dynamic",
        required: false,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "s3Access",
        label: "S3 Key",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "s3Secret",
        label: "S3 Secret",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      { key: "url", type: "string", description: "Resolvable URL of the file" },
      {
        key: "buffer",
        type: "any",
        description: "Buffer memory payload of downloaded file",
      },
    ],
    ["Connect your S3 key.", "Select operation.", "Map variables to paths."],
  ),

  // ================= AI =================
  createNode(
    "openai",
    "OpenAI",
    "ai",
    "bot",
    "openai",
    "Generate text, summaries, or structured data using OpenAI language models.",
    [
      {
        key: "prompt",
        label: "System Prompt",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "temperature",
        label: "Temperature",
        type: "number",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "apiKey",
        label: "OpenAI API Key",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "response.text",
        type: "string",
        description: "Completion output",
      },
      {
        key: "response.usage",
        type: "object",
        description: "Token utilization count",
      },
    ],
    [
      "Input your OpenAI Key.",
      "Build your dynamic master prompt.",
      "Ensure temperature maps to creativity need.",
    ],
  ),
  createNode(
    "anthropic",
    "Anthropic Claude",
    "ai",
    "brain-circuit",
    "anthropic",
    "Interact with Claude 3 Opus, Sonnet, or Haiku to analyze extensive contexts.",
    [
      {
        key: "prompt",
        label: "Prompt Command",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "model",
        label: "Claude Version",
        type: "select",
        options: ["claude-3-opus", "claude-3-sonnet", "claude-3-haiku"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "apiKey",
        label: "Anthropic API Key",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "response.text",
        type: "string",
        description: "Completion output",
      },
    ],
    [
      "Input API Key.",
      "Provide large data payloads into prompt.",
      "Extract answers.",
    ],
  ),
  createNode(
    "gemini",
    "Gemini",
    "ai",
    "sparkles",
    "google",
    "Leverage Google's multi-modal Gemini AI for reasoning generation.",
    [
      {
        key: "prompt",
        label: "Prompt",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "model",
        label: "Model",
        type: "select",
        options: ["gemini-1.5-pro", "gemini-1.5-flash"],
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "apiKey",
        label: "Gemini API Key",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "response.text",
        type: "string",
        description: "Generation result string",
      },
    ],
    ["Map keys.", "Test dynamic prompts."],
  ),
  createNode(
    "gemma",
    "Gemma Native",
    "ai",
    "cpu",
    "google",
    "Run smaller, open-weights models effectively.",
    [
      {
        key: "prompt",
        label: "Prompt String",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [],
    [
      {
        key: "response.text",
        type: "string",
        description: "Generation result",
      },
    ],
    ["Design lightweight logic.", "Run test."],
  ),
  createNode(
    "hugging_face",
    "Hugging Face Inference",
    "ai",
    "smile",
    "huggingface",
    "Execute custom open-source models deployed on Hugging Face infrastructure.",
    [
      {
        key: "endpointUrl",
        label: "Inference Endpoint",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "inputs",
        label: "Request Vector/Text",
        type: "dynamic",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "hfToken",
        label: "HF Access Token",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "predictions",
        type: "any",
        description: "Raw prediction array or completion from model structure",
      },
    ],
    ["Find endpoint URL.", "Format json standard vector."],
  ),

  // ================= SEND / OUTPUT =================
  createNode(
    "slack",
    "Slack",
    "send",
    "hash",
    "slack",
    "Send automated messages to channels or direct users.",
    [
      {
        key: "channelId",
        label: "Channel/User Target ID",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "text",
        label: "Markdown Message text",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "slackAuth",
        label: "Slack Bot Token",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "timestamp",
        type: "string",
        description: "Message delivery confirmation ts",
      },
    ],
    [
      "Setup Slack Auth.",
      "Identify the Channel ID.",
      "Construct dynamic mapped message.",
      "Send.",
    ],
  ),
  createNode(
    "send_email",
    "Send Email (SMTP)",
    "send",
    "send",
    null,
    "Dispatch automated emails using a custom SMTP server connection.",
    [
      {
        key: "to",
        label: "Recipient Email",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "from",
        label: "Sender Name",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "subject",
        label: "Subject",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "body",
        label: "Email HTML Body",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "smtpServer",
        label: "SMTP Server",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "port",
        label: "Port",
        type: "number",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "username",
        label: "Username",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "password",
        label: "Password",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [{ key: "status", type: "string", description: "Delivery outcome" }],
    ["Configure SMTP routes.", "Map dynamic elements.", "Test delivery block."],
  ),
  createNode(
    "twilio_sms",
    "Twilio SMS",
    "send",
    "message-square-text",
    "twilio",
    "Broadcast text messages via the Twilio telecom network.",
    [
      {
        key: "toPhone",
        label: "Target Phone Number",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "fromPhone",
        label: "Sender Phone / Active Number",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "message",
        label: "SMS Body String",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "accountSid",
        label: "Twilio Account SID",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "authToken",
        label: "Twilio Auth Token",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "messageId",
        type: "string",
        description: "Twilio confirmation record reference",
      },
    ],
    [
      "Input your live Twilio credentials.",
      "Insert valid E.164 phone numbers (e.g. +1234567890).",
    ],
  ),
  createNode(
    "hubspot_crm",
    "HubSpot CRM",
    "send",
    "contact",
    "hubspot",
    "Update or create customer lifecycle records inside HubSpot.",
    [
      {
        key: "objectType",
        label: "Target Object",
        type: "select",
        options: ["contacts", "companies", "deals"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "action",
        label: "Action Intent",
        type: "select",
        options: ["create", "update"],
        required: true,
        supportsDynamic: false,
      },
      {
        key: "properties",
        label: "Data Map (JSON)",
        type: "json",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "hubspotToken",
        label: "Private App Token / OAuth",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "recordId",
        type: "string",
        description: "Created or updated HubSpot internal ID references",
      },
    ],
    [
      "Authorize token.",
      "Decide object type routing.",
      "Pass strict JSON to override details.",
    ],
  ),
  createNode(
    "shopify_store",
    "Shopify Store",
    "send",
    "shopping-bag",
    "shopify",
    "Manage storefront elements like products, variants, and customer logic.",
    [
      {
        key: "endpoint",
        label: "Admin GraphQL / REST route",
        type: "text",
        required: true,
        supportsDynamic: false,
      },
      {
        key: "payload",
        label: "Mutation Payload",
        type: "json",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "shopAccessToken",
        label: "Admin API Token",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "response",
        type: "any",
        description: "Raw execution result from the shop store",
      },
    ],
    ["Provide Admin access token.", "Enter specific mutation."],
  ),
  createNode(
    "discord",
    "Discord",
    "send",
    "message-circle-dashed",
    "discord",
    "Blast updates directly into Discord server channels via Webhook or BoT.",
    [
      {
        key: "webhookUrl",
        label: "Discord Webhook URI",
        type: "text",
        required: false,
        supportsDynamic: true,
      },
      {
        key: "content",
        label: "Message Content",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "botToken",
        label: "Optional Bot Token",
        type: "password",
        required: false,
        supportsDynamic: false,
      },
    ],
    [{ key: "status", type: "string", description: "Success validation ping" }],
    [
      "Generate a webhook link in Discord interface.",
      "Drop it here immediately.",
    ],
  ),
  createNode(
    "x_twitter",
    "X (Twitter)",
    "send",
    "megaphone",
    "x",
    "Draft and publish tweets sequentially to an authorized timeline.",
    [
      {
        key: "tweetText",
        label: "Tweet Status Detail",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "twitterOauth",
        label: "X Connect Auth Handler",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "tweetId",
        type: "string",
        description: "The published tweet unique tag.",
      },
    ],
    ["Sign into your X logic portal.", "Submit standard text payload."],
  ),
  createNode(
    "linkedin",
    "LinkedIn",
    "send",
    "briefcase",
    "linkedin",
    "Post company or profile updates autonomously to your network.",
    [
      {
        key: "authorURN",
        label: "Author URN (Optional string)",
        type: "text",
        required: false,
        supportsDynamic: true,
      },
      {
        key: "postContent",
        label: "Text Payload",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "linkedinOauth",
        label: "LinkedIn Connect Auth",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "postLink",
        type: "string",
        description: "Resolvable URL of the new post.",
      },
    ],
    ["Confirm exact network identifier.", "Post execution details."],
  ),
  createNode(
    "instagram",
    "Instagram",
    "send",
    "camera",
    "instagram",
    "Deploy graphical payload content and carousel logic to timelines.",
    [
      {
        key: "imageUrl",
        label: "Image CDN URL",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "caption",
        label: "Associated Status Text",
        type: "textarea",
        required: false,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "instagramOauth",
        label: "Instagram Access Token",
        type: "oauth2",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "mediaId",
        type: "string",
        description: "FB graphical network ID.",
      },
    ],
    [
      "Confirm image exists at URL string.",
      "Run test logic node execution sequence.",
    ],
  ),
  createNode(
    "telegram",
    "Telegram",
    "send",
    "paperclip",
    "telegram",
    "Push robust direct messages globally over Telegram infrastructure protocols.",
    [
      {
        key: "chatId",
        label: "Direct Channel/Chat ID value",
        type: "text",
        required: true,
        supportsDynamic: true,
      },
      {
        key: "message",
        label: "Message Data String",
        type: "textarea",
        required: true,
        supportsDynamic: true,
      },
    ],
    [
      {
        key: "botKey",
        label: "Raw HTTP Bot Key String",
        type: "password",
        required: true,
        supportsDynamic: false,
      },
    ],
    [
      {
        key: "response",
        type: "object",
        description: "Raw validation API return.",
      },
    ],
    ["Use BotFather to obtain credentials.", "Supply exact ChatId numeric."],
  ),
];

fs.writeFileSync(
  "C:/Users/Acer/.gemini/antigravity/brain/c3325f35-4c86-49f0-a8fb-339ab7f87b9f/artifacts/complete-34-node-definitions.json",
  JSON.stringify(nodes, null, 2),
);
console.log(`Successfully generated JSON with length: ${nodes.length}`);
